FireMethodNotAllowed: true
#/api/user 和 /api/user/ 在不重定向的情况下(常用场景)拥有相同的处理器
DisableBodyConsumptionOnUnmarshal: true
DisablePathCorrection: true
TimeFormat: "Mon, 01 Jan 2006 15:04:05 GMT"
Charset: "UTF-8"
Other:
   Mysql:
      Host: "127.0.0.1"
      Port: "3306"
      User: "root"
      Password: "root"
      Database: "cms"
      Charset: "UTF8"
      TablePrefixt: "hs"
      MaxOpenConns: 100 #连接池最大连接数
      MaxIdleConns: 20 #连接池最大允许的空闲连接数
   Redis:
      Network: "tcp"
      Addr: "127.0.0.1:6379"
      Timeout: 30
      MaxActive: 10
      Password: ""
      Database: ""
      Prefix: ""
      Delim: "-"